### ISSUE TITLE
Crash Report when installed alongside Astral Sourcery

### ISSUE THREAD

**Issue by GreyMamoN** [Thutmose/Thut#78] opened 2017-11-30 17:58 UTC
**## Versions above 5.11.10 give an error
Forge 1.12.2 - 14.23.1.2556
The server is crashing
I apologize for the bad English ...**

> `Caused by: java.lang.ClassCastException: thut.api.terrain.CapabilityTerrain$DefaultProvider cannot be cast to hellfirepvp.astralsorcery.common.base.FluidRarityRegistry$ChunkFluidEntry
> 	at hellfirepvp.astralsorcery.common.base.FluidRarityRegistry.onChLoad(FluidRarityRegistry.java:122) ~[FluidRarityRegistry.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_620_FluidRarityRegistry_onChLoad_Load.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) ~[EventBus.class:?]
> 	... 15 more
> `

**Comment by Thutmose** [comment] 2017-11-30 19:50
That crash is caused by astralsourcery

**Comment by Thutmose** [comment] 2017-11-30 19:59
Hmm, though looking at how they do their checks, it shouldn't be occurring

**Comment by Daihok41** [comment] 2017-12-01 00:16
I am having same issue if i revert back to previous thut core 5.11.10 issue does not happen. It only started with the last couple thut core updates. Happens with 5.12.0 and 5.12.1

**Comment by Thutmose** [comment] 2017-12-01 04:03
ya, the latest thutcores (5.12.+) swapped over to using capabilities for some internal stuff, and somehow Astral Sourcery is trying to cast the thutcore chunk capabilities to its own type.

**Comment by crimso** [comment] 2017-12-01 04:41
Hello

I have the same problem when I want to load my SSP world, so should I report it to astral sourcery ?

Thank you

**Comment by Thutmose** [comment] 2017-12-01 13:23
yes, also report it there, then link this issue to the one you post there, hopefully this evening I will have time to try to look into what is going on, at first glance I don't see anything that either of the two mods are doing wrongly

**Comment by crimso** [comment] 2017-12-01 13:35
ok ok, the interesting thing is that If I use the older version from astral sorcery then is working ok so the problem is maybe on his side.

**Comment by Thutmose** [comment] 2017-12-01 13:37
ya, I didn't have time for a full check, but when I glanced at his code, and looked over mine, both seem to be done properly, so not entirely sure why the crash is occuring, but it is definitely an interaction of some kind going badly between the two mods

**Comment by HellFirePvP** [comment] 2017-12-01 20:46
I do my stuff properly aswell.

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/FluidRarityRegistry.java#L146
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/FluidRarityRegistry.java#L250

So where is this issue at? Both seem to properly set the capability at different registry names and check for their Capability-Instance.

**Comment by Thutmose** [comment] 2017-12-01 21:10
ya, and mine are here:
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/api/terrain/CapabilityTerrain.java#L86-L98
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/api/terrain/TerrainManager.java#L33-L48
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/core/common/ThutCore.java#L195

so I don't see anything that either of us are doing wrongly, probably something on forge's end?

**Comment by Thutmose** [comment] 2017-12-03 16:02
This has now been fixed in thutcore 5.12.3, thanks to @HellFirePvP for finding the error on my end :D

**Closed as completed by Thutmose** 2017-12-03 16:02 UTC
Labels: Compatiblity Issue
