### ISSUE TITLE
elevator block material dupe bug

### ISSUE THREAD

**Issue by mario308** [Thutmose/Thut#40] opened 2017-02-02 04:50 UTC
Every time I come back from the nether the floor the elevator is on gets duped with the blocks the elevator is made of. The portal to the nether and the elevator or both in the same chunk if that matters. This is similar to issue #36 but I am only getting the floor the elevator is on dupped.

Versions:
thutcore-3.11.1
thuttech-4.0.10.b

**Comment by PorkchopFu** [comment] 2017-02-02 23:08
My elevator floor was previously using DecoCraft glass blocks, but when I changed them to Minecraft vanilla glass blocks I found that my elevator would work, but that the blocks were duplicated from where the elevator was positioned at login. Breaking those duplicated blocks seems to work as a temporary solution, as I only need to do it once when I log in or after returning from being many cunks away from the elevator for an extended period.

I wonder if the duplication occurs when the chunk holding the elevator goes offline, which I believe happens when away from that chunk or offline for a certain period of time. If that is the case, a chunk loader like PersistentBits or ChickChunks may be a viable option that I'll try to test.

**Comment by PorkchopFu** [comment] 2017-02-02 23:11
On a side note, I wonder if Thutmose is on vacation or otherwise indisposed. I'd happily chip in for his time if I could get a nod that he's still working on the project.

**Comment by mario308** [comment] 2017-02-03 01:43
The blocks that I was using were factory blocks from the chisel mod. I tested this with a chunk loader and it seems to fix the issue. Thanks for the suggestion!

**Comment by Thutmose** [comment] 2017-08-11 08:34
this should be fixed now, it seems it was caused by some async chunk unloading issues.

**Closed as completed by Thutmose** 2017-08-11 08:34 UTC
