### ISSUE TITLE
Suffocation Damage Taken when a wall is next to the elevator.

### ISSUE THREAD

**Issue by WenXin20** [Thutmose/Thut#11] opened 2016-08-04 19:41 UTC
#### What happens:

Suffocation Damage
#### Steps to reproduce:
1. Make an elevator, with a wall on the corner.
2. Walk to the wall and start to take damage.

---
#### Affected Versions:
- Thut Core: 3.1.8
- Thut's Elevators (If Applicable): 3.0.9
- Forge: 2026-1.10.2
  ![2016-08-04_14 45 14](https://cloud.githubusercontent.com/assets/12000593/17416051/184e8412-5a52-11e6-8f55-9a1a9a4d80f0.png)

**Comment by WenXin20** [comment] 2016-09-28 03:46
Has this been looked at or fixed?

**Comment by Thutmose** [comment] 2016-09-28 04:01
I am not sure, I have been dealing with the disappearing ones, some of the collision code was changed recently, see if it has?

**Comment by WenXin20** [comment] 2016-09-28 04:48
Ok, I'll let you know

**Comment by WenXin20** [comment] 2016-09-28 19:33
Yep, I still take suffocation damage.

**Comment by Thutmose** [comment] 2016-09-28 19:59
Ok, I will look into getting this fixed now then.

**Comment by WenXin20** [comment] 2016-09-28 20:01
Thanks

**Comment by Thutmose** [comment] 2016-09-28 20:39
I Think I have found the cause if the issue, I am working on fix now.

**Comment by Thutmose** [comment] 2016-09-28 20:49
Testing fix for this now, then I will upload new version of ThutCore which fixes it.

**Comment by Thutmose** [comment] 2016-09-28 21:22
This has been fixed, will upload ThutCore 3.4.2 and Thuttech 4.0.5 which fix it shortly.

**Comment by Thutmose** [comment] 2016-09-28 21:28
Uploaded those to curse. closing this issue.

**Closed as completed by Thutmose** 2016-09-28 21:28 UTC

**Comment by WenXin20** [comment] 2016-09-28 23:34
Thanks
