### ISSUE TITLE
Set "view bobbing" to what it was before getting on elevator.

### ISSUE THREAD

**Issue by MechWarrior99** [Thutmose/Thut#24] opened 2016-11-09 04:59 UTC
View bobbing gets turned off when on an elevator, but does not get turned back on. It would be nice if it would check to see what the players setting was when they get on the elevator and then when they get off, set view bobbing to what ever it was at.

**Comment by Thutmose** [comment] 2016-11-09 05:27
this is a duplicate of #6

**Closed as completed by Thutmose** 2016-11-09 05:27 UTC
Labels: duplicate

**Comment by MechWarrior99** [comment] 2016-11-09 15:18
Oops sorry.
