### ISSUE TITLE
Crash when loading with both Baubles and Advanced Rocketry?

### ISSUE THREAD

**Issue by Keetarin** [Thutmose/Thut#82] opened 2017-12-20 16:22 UTC
When I installed Baubles and Advanced Rocketry together with Thut Wearables, Thut Wearables tries to convert advanced rocketry's Space Suit armor pieces into baubles despite them not being such thus throwing a crash. 
Even after turning off Baubles compatibility, Thut Wearables still tried to convert the space suit into a bauble.
I tested the offending mods in a pack with just them and all required API's but was unable to replicate it in the test pack... don't know why Thut Wearables is doing this.
Offending Mods: Baubles, Advanced Rocketry, Thut Wearables
Heres the Crash Log from the non-test pack (current build of a modpack i'm making): 
[crash-2017-12-20_09.06.40-client.txt](https://github.com/Thutmose/Thut/files/1576264/crash-2017-12-20_09.06.40-client.txt)
Edit: It's happened again, after it had just stopped happening, it seems they don't want to play nice....
[crash-2017-12-20_09.35.22-client.txt](https://github.com/Thutmose/Thut/files/1576322/crash-2017-12-20_09.35.22-client.txt)

**Comment by Thutmose** [comment] 2017-12-20 16:38
This is odd, shouldn't happen, I will look into what is going wrong here...

**Comment by Thutmose** [comment] 2017-12-20 16:44
This definitely does not occur with just the offending mods:
![image](https://user-images.githubusercontent.com/2363472/34218032-1ef5309e-e57b-11e7-8af4-0f11eb2e4c3f.png)

Some other mod is badly returning some value for its capability

**Comment by Keetarin** [comment] 2017-12-20 16:45
Thanks for looking in to it, I need Thut Wearables due to this pack being centered on Tech mods and Pokecube.

**Comment by Keetarin** [comment] 2017-12-20 16:45
I'll send the pack to you for testing, most of the mods I'm planning to use are currently disabled due to the pack being in a heavy testing phase.
Edit: From what i've seen on my end, the bug appears to be intermittent, though it does seem to be showing up often to me.

**Comment by Thutmose** [comment] 2017-12-20 16:49
this is where the crash is occuring:
https://github.com/Thutmose/ThutWearables/blob/1.12/src/main/java/thut/wearables/compat/baubles/Compat.java#L53-L57
specifically on line 56, the crash means some mod has returned true for having the wearables capability, but is then returning the item for the getCapability call...

**Comment by Keetarin** [comment] 2017-12-20 16:53
Huh... Okay, the only mods I know of that I know of in my pack that has wearables capability with a cap in it would be the pokecube mods, but that can't be it.... gimme a mo while I test the bauble side of things (assuming the bug doesn't hide itself from me again :( )

**Comment by Thutmose** [comment] 2017-12-20 16:55
it could be an issue with any itemstack capability, I had a bug in one of my mods related to chunk capabilities with a typo in the hasCapability check, so another mod could have done similar

**Comment by Keetarin** [comment] 2017-12-20 16:55
Ah! nearly forgot to give the pack to you!
[Pokecube Survival (Name Pending)-1.0.zip](https://github.com/Thutmose/Thut/files/1576375/Pokecube.Survival.Name.Pending.-1.0.zip)
Edit: It's easier to find a bug when both people have a copy of the proverbial map.

**Comment by Thutmose** [comment] 2017-12-20 16:57
in the mean time while that is downloading, I will check the pokecube ones to see if they are the issue

**Comment by Keetarin** [comment] 2017-12-20 16:58
Thanks for helping me look into this, this bug is a pain in the ***.

**Comment by Thutmose** [comment] 2017-12-20 17:00
not caused directly by any of the pokecube mods:
![image](https://user-images.githubusercontent.com/2363472/34218828-4be09092-e57d-11e7-82d0-96eedee5a3dc.png)
![image](https://user-images.githubusercontent.com/2363472/34218844-5b8c14da-e57d-11e7-8f3e-7c734c6172a6.png)

**Comment by Keetarin** [comment] 2017-12-20 17:04
Okay, this is strange...
I've sent a copy of the pack to you earlier on, so It should contain a list (mainly in the crash logs) of the mods I was testing at the time as well as the means to get the mods quickly. I honestly don't know of any of the mods aside from pokecube having direct wearables compatibility, after all, I've used baubles for most of my personal packs.
Edit: I just woke up about an hour ago, so my brain is going a bit slow...

**Comment by Thutmose** [comment] 2017-12-20 17:06
the pack you sent as is, doesn't seem to have this crash, one thing I did notice was the inclusion of Pokecube Alternative, a word of warning, that mod is not balanced for survival use, it is intended for adventure mode

**Comment by Keetarin** [comment] 2017-12-20 17:08
Really? I didn't know that (about pokecube alternative), I'll remove that for now since honestly I don't want build an adventure pack.
Still, where could that bug be hiding???

**Comment by Thutmose** [comment] 2017-12-20 17:09
Ya, a main balance point in pokecube is that the pokemobs use up inventory slots, alternative makes them have their own slots, so that balance is gone.

I am checking with all of the mods enabled

**Comment by Thutmose** [comment] 2017-12-20 17:11
heh never mind testing with all of them enabled, at least one of them has a major issue:

https://gist.github.com/Thutmose/803cc07f1a6552618ef6c3e71cea6aea

no indication of which from the report either...

**Comment by Keetarin** [comment] 2017-12-20 17:14
@ Previous Comment: Thanks, honestly, while I'm good at putting together a stable pack, trying to find a bug that doesn't show where it's from is kinda beyond me... *sigh* looks like I'll have to disable baubles for now on my end.
@ Current Comment: That looks similar to the error I got when I tried to have Immersive Engineering in the pack??? I know for a fact that I had removed that. Do you know which mod you enabled before that error got thrown, or did you simply enable them all at the same time?

**Comment by Thutmose** [comment] 2017-12-20 17:16
I just enabled all of them at once, I use IE in my poke-tech survival modpack, so it shouldn't be related to that, let me test it with baubles as well

**Comment by Keetarin** [comment] 2017-12-20 17:17
Huh? Is that error related to multiblocks by chance?
Edit: Multiblock Structures...

**Comment by Thutmose** [comment] 2017-12-20 17:17
IE + Baubles + Wearables + Pokecube set seems to work fine:

![image](https://user-images.githubusercontent.com/2363472/34219618-c9d05f62-e57f-11e7-9b6d-c156bb383083.png)

**Comment by Keetarin** [comment] 2017-12-20 17:19
Okay, this is getting weird. 
The error you got, do you know what it specifically refers to in terms of type of thing in-game: multiblocks, items, or somesuch?

**Comment by Thutmose** [comment] 2017-12-20 17:21
No idea, that is some internal forge thing for loading in the model jsons

**Comment by Keetarin** [comment] 2017-12-20 17:21
Curses, *sigh*, still better than nothing I suppose.

**Comment by Thutmose** [comment] 2017-12-20 17:22
you have 20 coremods as well, so it could be caused by one of them messing with the wrong thing

**Comment by Keetarin** [comment] 2017-12-20 17:25
True, but at the moment, only the mods specified in the crash log are enabled for testing at this stage, so really it could only be one of those if it is.

**Comment by Thutmose** [comment] 2017-12-20 17:29
I would suggest going through them and seeing if you can find out which one is causing the crash, it should happen every time you load the game with a space suit in your inventory if the offending mod is active

**Comment by Keetarin** [comment] 2017-12-20 17:31
Sure. Though that would take time... and I do believe I've mentioned above that the bug sometimes does not show. Still at least I now know that the it's not any of the three mods that were showing themselves as offenders.

**Comment by Keetarin** [comment] 2017-12-20 17:31
I'll get back to you in about an hour after testing what's currently enabled.
Edit: I hate being tired in the morning, my brain goes so slowly :( so many edits

**Comment by Thutmose** [comment] 2017-12-20 17:37
good luck with the testing

**Comment by Keetarin** [comment] 2017-12-20 18:45
Looks like I may have found the culprit, it appears to be IC2 from the initial tests, I'll remove IC2 and all that require it as a test later. For now, lunch time.

**Comment by Keetarin** [comment] 2017-12-20 20:06
I tested it and it indeed was IC2, also just to confirm whether or not Immersive Engineering was a problem I put it in a test pack by itself.... I'll be sending the crash log to the creator of the mod, but I thought you would like to see it since it might effect your pack.
[crash-2017-12-20_13.03.15-client.txt](https://github.com/Thutmose/Thut/files/1576869/crash-2017-12-20_13.03.15-client.txt)
Edit: Forgot to mention which version of IE & forge *smacks head* 
IE 0.12 - 75
Forge-14.23.1.2578

**Comment by Thutmose** [comment] 2018-01-01 22:55
Closing this issue then, hopefully they get it fixed

**Closed as completed by Thutmose** 2018-01-01 22:55 UTC
